In [1]:
import numpy as np

In [4]:

A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))
b = np.array([7, 1], dtype=np.dtype(float))
b.shape


(2,)

In [5]:
x = np.linalg.solve(A, b)
x

array([-1.,  2.])

In [7]:
d = np.linalg.det(A)
d

-11.000000000000002

In [10]:
# elimination method
A_system = np.hstack((A,b.reshape(2,1)))
A_system

array([[-1.,  3.,  7.],
       [ 3.,  2.,  1.]])

In [11]:
A_system_res = A_system.copy()

In [12]:
A_system_res[1]  = 3 * A_system_res[0]+A_system_res[1]

In [15]:
A_system_res

array([[-1.,  3.,  7.],
       [ 0.,  1.,  2.]])

In [14]:
A_system_res[1] = 1/11 * A_system_res[1]

In [16]:
# LE with no solutions
A_2 = np.array([
        [-1, 3],
        [3, -9]
    ], dtype=np.dtype(float))

b_2 = np.array([7, 1], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: -0.00


In [18]:

try:
    x_2 = np.linalg.solve(A_2, b_2)
except np.linalg.LinAlgError as err:
    print(err)
x_2

array([1.32105589e+17, 4.40351964e+16])

In [19]:
# LE with infinite many solutions
b_3 = np.array([7, -21], dtype=np.dtype(float))

A_3_system = np.hstack((A_2, b_3.reshape((2, 1))))
print(A_3_system)

# copy() matrix.
A_3_system_res = A_3_system.copy()

# Multiply row 0 by 3 and add it to the row 1.
A_3_system_res[1] = 3 * A_3_system_res[0] + A_3_system_res[1]
print(A_3_system_res)

[[ -1.   3.   7.]
 [  3.  -9. -21.]]
[[-1.  3.  7.]
 [ 0.  0.  0.]]


In [20]:
try:
    ans = np.linalg.solve(A_2,b_3)
except np.linalg.LinAlgError as err:
    print(err)
ans


array([4.44089210e-16, 2.33333333e+00])

In [31]:
# quiz question
# 2b+3m = 15g
# 2b+4m = 16g
quiz_array = np.array(([2,3],[2,4]),np.dtype(float))
quiz_b_array = np.array([15,16],np.dtype(float))
ans = np.linalg.solve(quiz_array,quiz_b_array)
det = np.linalg.det(quiz_array)
ans
# det

array([6., 1.])

In [38]:
# next question with new weights
# 2b+1m+5c = 20g
# 1b+2m+1c = 10g
# 2b+1m+3c = 15g
quiz_array = np.array(([2,1,5],[1,2,1],[2,1,3]),np.dtype(float))
quiz_b_array = np.array([20,10,15],np.dtype(float))
ans = np.linalg.solve(quiz_array,quiz_b_array)
det = np.linalg.det(quiz_array)
# det
ans

array([2.5, 2.5, 2.5])

In [40]:
quiz_array = np.array(([1,2,3],[0,2,2],[1,4,5]),np.dtype(float))
quiz_b_array = np.array([20,10,15],np.dtype(float))
# ans = np.linalg.solve(quiz_array,quiz_b_array)
det = np.linalg.det(quiz_array)
det
# ans

0.0